---
title: "Component correlations"
author: "Lukáš 'hejtmy' Hejtmánek"
date: "25/03/2020"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile),
                        output_dir = "../docs", 'analysis.html'))})
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---
```{r setup, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(navr)
library(plotly)
library(crosstalk)
library(dplyr)
library(knitr)
library(tidyr)
sapply(list.files("../functions", full.names = T, recursive = T), source)
data_dir <- "E:/OneDrive/NUDZ/projects/HCENAT/Data/"
img_path <- "../images/megamap5.png"
```

```{r loading-data, message=FALSE, echo=FALSE, warning=FALSE}
options(gargle_oauth_email = "hejtmy@gmail.com")
df_preprocessing <- load_participant_preprocessing_status()

# Load components
folder <- file.path(data_dir, "../MRI-data-tomecek/filtered")
names_file <- file.path(data_dir, "../MRI-data-tomecek/subs_20190830_1422.txt")
components <- load_mri(folder, names_file)
components <- rename_mri_participants(components, df_preprocessing)
fmri <- restructure_mri(components)
component_names <- names(components)

participant_names <- names(components[[1]])
good_participants <- c()
for(name in participant_names){
  code <- fmri_code(name, df_preprocessing)
  if(!df_preprocessing$session1_ok[df_preprocessing$ID == name]){
    message("Skipping participant ", name, "/", code, ". Doesn't have a valid session behavioral data\n")
  } else {
    good_participants <- c(good_participants, name)
  }
}
remove(participant_names)

hrf_names <- c("moving", "pointing", "still")
hrf_folder <- file.path("..", "exports", "hrf")
speed_folder <- file.path("..", "exports", "speeds")
rotation_folder <- file.path("..", "exports", "rotations")
hrfs <- list()
for(name in good_participants){
  code <- fmri_code(name, df_preprocessing)
  f <- file.path(speed_folder, paste0(code, "_speed.txt"))
  #' Speeds have blank lines where there was too many missing values
  hrfs[[name]]$speed <- scan(f, what = numeric(), n = 400, sep = "\n", fill = NA_real_,
                             blank.lines.skip = FALSE, quiet = TRUE)
  f <- file.path(rotation_folder, paste0(code, "_rotation.txt"))
  rotation <- read.table(f, sep=",", header = TRUE)
  hrfs[[name]]$rotation_x <- rotation$x
  hrfs[[name]]$rotation_total <- rotation$total
  for(hrf in hrf_names){
    f <- file.path(hrf_folder, paste0(code, "_", hrf, ".txt"))
    hrfs[[name]][[hrf]]<- scan(f, n = 400, sep="\n", quiet = TRUE)
    if(length(hrfs[[name]][[hrf]]) != 400){
      warning(name, " ", hrf, " has length ", length(hrfs[[hrf]][[name]]))
    }
  }
}
```

```{r calculate-correlations}
correlations <- data.frame(stringsAsFactors = FALSE)
for(name in good_participants){
  participant_series <- hrfs[[name]]
  comps <- sapply(components, function(x){x[[name]]}, USE.NAMES = TRUE, simplify = FALSE)
  for(series_name in names(participant_series)){
    series <- participant_series[[series_name]]
    res <- sapply(comps, function(x){cor(x, series, use = "complete.obs")}, simplify = FALSE)
    res$participant <- name
    res$event <- series_name
    correlations <- rbind(correlations, as.data.frame(res))
  }
}

```

```{r averaging-correlations}
cor_long <- correlations %>%
  pivot_longer(cols = -c(participant, event),names_to = "component")
avg_cor <- cor_long %>%
  group_by(event, component) %>%
  summarize(average = mean(value))
```

-------------------------------------------------

#### Overview
Vlevo jsou boxploty za všechny komponenty. Je nutné nejdřív vybrat patřičný event, v defaultu je to vykreselno na půrměr pro všechny. Tečky jsou jednotlivé korelace pro daný event a komponentu pro jednoho participanta. Jedná se o Pearsonovy korelace. 

Vpravo je pak možnost vybrat konkrétní komponentu a podívat se, jak reaguje v různých situacích. V základu je tam opět vykresleno vše, je nutné zvolit jednu konkrétní komponentu.

-----------------------------------------------

### Summative visualisation

```{r}
shared_cor_long_events <- cor_long %>% SharedData$new()

widgets <- bscols(widths = c(12, 12, 12),
  filter_select("event", "Event", shared_cor_long_events, ~event, multiple = FALSE)
)

shared_cor_long_events_2 <- cor_long %>% SharedData$new()

widgets2 <- bscols(widths = c(12, 12, 12),
  filter_select("event", "Event", shared_cor_long_events_2, ~event, multiple = FALSE)
)
bscols(
  list(
    widgets,
    plot_ly(data = shared_cor_long_events, x=~component, y=~value, color=~component) %>%
      add_trace(type="box", hoverinfo="y", showlegend=FALSE, 
                boxmean=TRUE, boxpoints="all", jitter=1,
                boxpoints=TRUE, hoveron="boxes"),
    widgets2,
    plot_ly(data = shared_cor_long_events_2, x=~component, y=~value, color=~component) %>%
        add_trace(type="box", hoverinfo="y", showlegend=FALSE, 
                  boxmean=TRUE, boxpoints="all", jitter=1,
                  boxpoints=TRUE, hoveron="boxes")
  )
)
```

### Separate fMRI conponent

```{r}
shared_cor_long <- cor_long %>%
  SharedData$new()

widgets <- bscols(widths = c(12, 12, 12),
  filter_select("component", "Component", shared_cor_long, ~component, multiple = FALSE)
)

bscols(
  list(
    widgets,
      plot_ly(data = shared_cor_long, x=~event, y=~value, color=~component) %>%
        add_trace(type="box", boxpoints = "all", jitter = 0.3, showlegend=FALSE)
  )
)
```