---
title: "Interactive report of the beta coefficients"
author: "Lukáš 'hejtmy' Hejtmánek"
date: "25/03/2020"
knit: (function(inputFile, encoding) { 
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile),
                        output_dir = "../docs", 'manuscript-interactive-report.html'))})
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
---
```{r setup, message=FALSE, warning=FALSE, results='hide', echo=FALSE}
library(plotly)
library(crosstalk)
library(knitr)
library(tidyverse)

p_to_stars <- function(values){
  func <- function(value){
    if(value >= 0.05) return("-")
    if(value < 0.001) return("***")
    if(value < 0.01) return("**")
    if(value < 0.05) return("*")
  }
  return(sapply(values, func))
}

df_beta <- read.table("../summaries/first-order-beta.csv",
                                  header = TRUE, sep = ";")

df_beta <- df_beta %>%
  select(-c(p.value, std.error, statistic)) %>%
  mutate(component = factor(as.numeric(gsub("filt_component_", "", component))))

levels(df_beta$component) <- paste0("component_", levels(df_beta$component))

df_beta <- df_beta %>%
  group_by(term, component) %>%
  summarise(avg = mean(estimate), 
            p_value = wilcox.test(estimate, mu = 0)$p.value,
            .groups="drop") %>%
  mutate(p_value = p.adjust(p_value, method = "fdr"),
         sig = p_to_stars(p_value)) %>%
  right_join(df_beta, by=c("term", "component"))

## Contrasts ---
df_cont <- df_beta %>%
  select(term, estimate, participant, component) %>%
  pivot_wider(names_from = term, values_from = estimate) %>%
  mutate(cont_mov_0 = moving.trial + moving.learn,
         cont_mov_trial_learn = moving.trial - moving.learn,
         cont_point_trial_learn = pointing.trial - pointing.learn,
         cont_point_0 = pointing.trial + pointing.learn) %>%
  pivot_longer(cols = -c(participant, component),
               names_to = "term",
               values_to = "estimate")

out <- df_cont %>%
  filter(grepl("0", term)) %>%
  group_by(term, component) %>%
  summarise(avg = mean(estimate), 
            p_value = wilcox.test(estimate, mu = 0)$p.value,
            .groups="drop")

out2 <- df_cont %>%
  pivot_wider(names_from = term, values_from=estimate) %>%
  group_by(component) %>%
  summarise(cont_mov_trial_learn = wilcox.test(moving.trial, moving.learn, paired = TRUE)$p.value,
            cont_point_trial_learn = wilcox.test(pointing.trial, pointing.learn, paired = TRUE)$p.value,
          .groups="drop") %>%
  pivot_longer(cols = -component, names_to="term", values_to = "p_value")

out2 <- df_cont %>%
  filter(grepl("trial_learn", term)) %>%
  group_by(term, component) %>%
  summarise(avg = mean(estimate)) %>%
  right_join(out2, by=c("term", "component"))

out3 <- rbind(out, out2) %>%
  mutate(p_value = p.adjust(p_value, method = "fdr"),
         sig = p_to_stars(p_value))

df_cont <- df_cont %>%
  right_join(out3, by=c("term", "component"))

df_beta <- rbind(df_beta, df_cont)
```

```{r eval =FALSE}

mutate(`movement.trial > movement.learn` = paste(ifelse(sign_mov_trial, "+", "-"), p_mov_trial_learn),
       `movement > 0` = paste(ifelse(sign_mov_0, "+", "-"), p_mov_0),
       `pointing.trial > pointing.learn` = paste(ifelse(sign_point_trial, "+", "-"), p_point_trial_learn),
       `pointing > 0` = paste(ifelse(sign_point_0, "+", "-"), p_point_0))
```
-------------------------------

#### Overview
Uses first order beta coefficients

Row {data-height=600}
---------------------------

### All components
```{r}
shared_beta <- SharedData$new(df_beta)
shared_beta2 <- SharedData$new(df_beta)
```

```{r}
selection_widget <- bscols(
  widths = 12,
  filter_select("event", "Event", shared_beta, ~term, multiple = FALSE)
)
selection_widget
plot_ly(shared_beta, x = ~component, y = ~estimate, color = ~sig) %>%
  add_trace(type = "box", hoverinfo = "x+y", showlegend = TRUE, boxmean = TRUE,
            boxpoints = "all", jitter = 1, boxpoints = TRUE, hoveron = "boxes") %>%
  layout(height = 500, yaxis=list(range=c(-1.2,1.2)))
```


Row {data-height=800}
---------------------------------
### new text

```{r}
selection_widget2 <- bscols(
  widths = 12,
  filter_select("component", "Component", shared_beta2, 
                ~component, multiple = FALSE)
)
selection_widget2
shared_beta2 %>%
  plot_ly(x=~term, y=~estimate, color=~sig) %>%
    add_trace(type = "box", hoverinfo = "x+y", showlegend = TRUE,
              boxpoints = "all", jitter = 1, boxpoints = TRUE, hoveron = "boxes") %>%
  layout(autosize = TRUE, height = 400,
         xaxis = list(autorange = TRUE))
```

### Component

```{r, results='asis'}
knitr::raw_html('
    <div class="slidecontainer">
  <input type="range" min="1" max="58" value="1" class="slider-square" id="component-slider">
</div>
<div id="id-component">

</div>
<div id="image-swap"></div>
<script>
var slider = document.getElementById("component-slider");
var output = document.getElementById("id-component");
output.innerHTML = slider.value; // Display the default slider value

// Update the current slider value (each time you drag the slider handle)
slider.oninput = function() {
  output.innerHTML = this.value;
  setImage(this.value);
}
function setImage(value){
    var div = document.getElementById("image-swap");
    div.innerHTML =  "";
    div.appendChild(createImage(value));
}
function createImage(value){
    let img = document.createElement("img"); 
    image_pth = "img/component_" + value + ".png";
	img.src = image_pth;
    return(img);
}
</script>')
```

