---
title: "movement report"
author: "Lukáš 'hejtmy' Hejtmánek"
date: "24/10/2019"
output: html_document
---
```{r, setup, echo=F, warning=F, message=FALSE}
library(data.table)
library(navr)
library(dplyr)
library(ez)
library(knitr)
sapply(list.files("../functions", full.names = T, recursive = T), source)
CORRECT_ANGLES <- read.table("../data/correct-angles.csv", sep=",", header=TRUE)
data_dir <- "E:/OneDrive/NUDZ/projects/HCENAT/Data/"
img_path <- "../images/megamap5.png"
df_preprocessing <- read.table("../data/df_preprocessing-24.10.2019.csv", sep=";", header=TRUE, stringsAsFactors = FALSE)

## Unity loading -----
participants <- load_participants(data_dir, df_preprocessing = df_preprocessing, sessions = 1)
participants <- add_pulses.participants(participants)

## MRI loading ------
folder <- file.path(data_dir, "../MRI-data-tomecek/filtered")
names_file <- file.path(data_dir, "../MRI-data-tomecek/subs_20190830_1422.txt")
components <- load_mri(folder, names_file)
components <- rename_mri_participants(components, df_preprocessing)
fmri <- restructure_mri(components)
```

```{r, echo=F, warning=F, message=FALSE}
## fmri analysis ----
component_names <- c("filt_cen_11", "filt_cen_16", "filt_cen_23", "filt_cen_37", 
                     "filt_cen_39", "filt_cen_46", "filt_dmn_2", "filt_dmn_51", 
                     "filt_dmn_52","filt_hpc_12", "filt_hpc_54", "filt_hpc_56", 
                     "filt_mot_33", "filt_sn_31",  "filt_sn_8", "filt_unk_10", 
                     "filt_vis_4", "filt_vis_43")
movement_pulses <- create_movement_stop_pulses_table(participants, 3,0.2,3)
movement_fmri <- get_fmri(fmri, movement_pulses)
```

```{r, echo=F}
for(component_name in component_names){
  eval(parse(text=
     paste0("ez_res <- ezANOVA(pointing_fmri,
        dv =", component_name,",
        wid = participant,
        within = movement_type,
        return_aov=TRUE)")))
  print(summary(ez_res$aov))
  print(ggplot(pointing_fmri, aes(participant, .data[[component_name]], fill=movement_type)) + geom_boxplot())
  print(ggplot(pointing_fmri, aes(correct, .data[[component_name]])) + geom_boxplot())
}
```